import './styles/styles.css'
import './styles/calendar.css'

import './scripts/ui.js'
import './scripts/showTip.js'
import './scripts/addtask_modal.js'
import './scripts/taskManager.js'
import './scripts/loadTasks.js'
import './scripts/task_view.js'
import './scripts/calendar.js'
import './scripts/export.js'
import './scripts/import.js'